export type Theme = "dark" | "light";
export type Accent = "green" | "indigo" | "amber" | "magenta";
export type Density = "compact" | "regular" | "cozy";
export type Lang = "en" | "ar";

export interface Tweaks {
  theme: Theme;
  accent: Accent;
  density: Density;
  lang: Lang;
  collapsed: boolean;
  showAIPersonality: boolean;
}

export type RouteId =
  | "dashboard"
  | "inbox"
  | "calendar"
  | "social"
  | "media"
  | "pipeline"
  | "campaigns"
  | "ads"
  | "contacts"
  | "analytics"
  | "templates"
  | "team"
  | "settings"
  | "admin";

// ─── Pipeline / Tickets API shapes ────────────────────────────────────────

export type StageColor = "ink" | "info" | "ok" | "warn" | "bad" | "accent" | "human";

export interface TicketStage {
  id: string;
  pipelineId: string;
  key: string;
  label: string;
  labelAr: string;
  color: StageColor;
  order: number;
  groupKey: "new" | "discovery" | "quoted" | "payment" | "fulfill" | "done" | string;
  isTerminal: boolean;
  isWon: boolean;
  slaMinutes: number | null;
}

export interface Pipeline {
  id: string;
  key: string;
  name: string;
  nameAr: string;
  isDefault: boolean;
  stages: TicketStage[];
  _count?: { tickets: number };
}

export interface TicketContact {
  id: string;
  name: string;
  phone: string;
  industry: string;
}

export interface Ticket {
  id: string;
  number: number;
  pipelineId: string;
  stageId: string;
  contactId: string;
  conversationId: string | null;
  ownerId: string | null;
  title: string;
  description: string | null;
  value: number | null;
  currency: string;
  lostReason: string | null;
  createdAt: string;
  updatedAt: string;
  closedAt: string | null;
  enteredStageAt: string;
  contact?: TicketContact;
  stage?: TicketStage;
}

export interface TicketsListPage {
  items: Ticket[];
  nextCursor: string | null;
}

export interface TicketActivity {
  id: string;
  ticketId: string;
  kind: "created" | "stage_changed" | "owner_changed" | "value_changed" | "note" | "won" | "lost";
  note: string | null;
  fromStage: string | null;
  toStage: string | null;
  byUserId: string | null;
  createdAt: string;
}

export interface TicketDetail extends Ticket {
  pipeline: Pipeline;
  activities: TicketActivity[];
}

export interface TicketsDashboardSummary {
  openValue: number;
  currency: string;
  winRate: number;
  wonCount: number;
  lostCount: number;
  avgCloseHours: number;
  totalTickets: number;
}

export type ConvChannel = "whatsapp" | "instagram" | "facebook" | "tiktok" | "webchat";

export const CHANNEL_LABEL: Record<ConvChannel, string> = {
  whatsapp:  "WhatsApp",
  instagram: "Instagram",
  facebook:  "Facebook",
  tiktok:    "TikTok",
  webchat:   "Web chat",
};

export type SocialPlatform = "facebook" | "instagram" | "tiktok";

export const PLATFORM_LABEL: Record<SocialPlatform, string> = {
  facebook:  "Facebook",
  instagram: "Instagram",
  tiktok:    "TikTok",
};

export interface SocialComment {
  id: string;
  author: string;
  authorHandle: string;
  body: string;
  bodyAr?: string;
  likes: number;
  at: string;     // human-readable like "2h"
  liked?: boolean;
  accountId?: string | null;
}

export interface SocialPost {
  id: string;
  platform: SocialPlatform;
  author: string;
  authorHandle: string;
  authorVerified?: boolean;
  body: string;
  bodyAr?: string;
  mediaLabel?: string; // text label for the placeholder image
  postedAt: string;
  likes: number;
  shares: number;
  views?: number;       // tiktok-style
  comments: SocialComment[];
}

export interface TeamMember {
  id: string;
  name: string;
  role: string;
  initials: string;
  color: string;
}

export interface Contact {
  id: string;
  name: string;
  phone: string;
  tags: string[];
  industry: string;
  lifecycle: string;
  lastSeen: string;
  source: string;
  convs: number;
  value: string;
}

export type DeliveryStatus = "sent" | "delivered" | "read" | "failed";

export interface Message {
  /**
   * 'ai' is a reply generated by the Kewy AI agent. It is outbound like
   * 'human' — the salon speaking — but must stay visually distinguishable so
   * staff never mistake a generated answer for a colleague's.
   */
  from: "them" | "human" | "ai";
  t: string;
  /** ISO timestamp from the server — drives the thread's day separators. */
  createdAt?: string;
  body: string;
  attach?: string;
  /**
   * Who/what produced an outbound message, e.g. "kewy-ai (shadow)". The shadow
   * suffix means the reply was logged for review and never delivered.
   */
  agent?: string | null;
  metaMessageId?: string | null;
  deliveryStatus?: DeliveryStatus | null;
  deliveryStatusAt?: string | null;
}

export interface Conversation {
  id: string;
  contactId: string;
  /** Kewy AI is answering this thread. Defaults false; opt-in per conversation. */
  aiEnabled?: boolean;
  /** Set when a human replied into an AI thread — the agent backs off until cleared. */
  aiPausedAt?: string | null;
  unread: number;
  pinned: boolean;
  lastAt: string;
  lastFrom: "them" | "human";
  preview: string;
  channel: ConvChannel;
  status: "human" | "closed" | "spam";
  intent: string;
  confidence: number;
  escalated?: boolean;
  messages?: Message[];
  // WhatsApp-only: backend populates these when channel === "whatsapp".
  lastInboundAt?: string | null;
  waWindowOpen?: boolean;
}

export type AppointmentStatus =
  | "confirmed"
  | "pending"
  | "completed"
  | "cancelled"
  | "no-show";

export interface Appointment {
  id: string;
  contactId: string;
  staffId?: string;
  service: string;
  serviceAr: string;
  startAt: string;          // ISO 8601
  durationMin: number;
  status: AppointmentStatus;
  source: "human" | "self-booking";
  note?: string;
  noteAr?: string;
  reminderSent?: boolean;
}

export interface Campaign {
  id: string;
  name: string;
  status: "running" | "scheduled" | "draft" | "completed" | "paused";
  audience: string;
  recipients: number;
  sent: number;
  delivered: number;
  read: number;
  replied: number;
  conversions: number;
  channel: string;
  schedule: string;
  segmentId: string | null;
  templateId: string | null;
}

export interface Intent {
  name: string;
  pct: number;
  count: number;
}

export type TemplateButtonType = "QUICK_REPLY" | "URL" | "PHONE_NUMBER";
export interface TemplateButtonDef {
  type: TemplateButtonType;
  text: string;
  url?: string;
  phone_number?: string;
}

export interface Template {
  id: string;
  name: string;
  lang: Lang;
  category: "TRANSACTIONAL" | "UTILITY" | "MARKETING" | "AUTHENTICATION";
  status: "approved" | "pending" | "rejected" | "submitted" | "failed";
  uses: number;
  body?: string | null;
  footer?: string | null;
  headerType?: string | null;
  headerContent?: string | null;
  // Stored as JSON string on the server; the API hands it back unparsed.
  buttons?: string | null;
}

// ─── Segments ─────────────────────────────────────────────────────────────

export interface SegmentFilter {
  lifecycle?: string[];
  industry?: string[];
  source?: string[];
  tagsAll?: string[];
  tagsAny?: string[];
  search?: string;
  hasPhone?: boolean;
  /** Contact has at least one deal currently in any of these stage keys. */
  stageAny?: string[];
}

/** crm = saved filter (re-evaluated), manual = user-picked membership,
 *  hjz = membership snapshot pushed by the HJZ sync (read-only here). */
export type SegmentOrigin = "crm" | "manual" | "hjz";

export interface Segment {
  id: string;
  name: string;
  nameAr: string | null;
  color: string | null;
  origin: SegmentOrigin;
  filter: SegmentFilter;
  count: number;
  createdAt: string;
  updatedAt: string;
}

// ─── Tags ─────────────────────────────────────────────────────────────────

export interface TagRow {
  id: string;
  name: string;
  color: string;
  usageCount: number;
}

// ─── Notes ────────────────────────────────────────────────────────────────

export interface Note {
  id: string;
  contactId: string;
  conversationId: string | null;
  ticketId: string | null;
  body: string;
  authorUserId: string | null;
  createdAt: string;
  updatedAt: string;
}

// ─── Workspaces ───────────────────────────────────────────────────────────

export type WorkspaceRole = "owner" | "admin" | "agent" | "viewer";

export interface Workspace {
  id: string;
  name: string;
  slug: string;
  timezone: string;
  lang: string;
  plan: string;
  role: WorkspaceRole;
}

// ─── Admin portal (super-admin views) ─────────────────────────────────────

export interface AdminWorkspaceRow {
  id: string;
  name: string;
  slug: string;
  plan: string;
  lang: string;
  timezone: string;
  suspendedAt: string | null;
  createdAt: string;
  updatedAt: string;
  owner: { id: string; email: string; name: string } | null;
  counts: {
    members: number;
    contacts: number;
    conversations: number;
    tickets: number;
  };
}

export interface AdminWorkspaceDetail {
  id: string;
  name: string;
  slug: string;
  plan: string;
  lang: string;
  timezone: string;
  suspendedAt: string | null;
  createdAt: string;
  updatedAt: string;
  members: Array<{
    id: string;
    role: WorkspaceRole;
    user: {
      id: string;
      email: string;
      name: string;
      initials: string;
      color: string;
      status: string;
      isSuperAdmin: boolean;
    };
  }>;
  integrations: Array<{
    id: string;
    platform: string;
    pageId: string | null;
    pageName: string | null;
    expiresAt: string | null;
    lastFetchedAt: string | null;
  }>;
  _count: {
    contacts: number;
    conversations: number;
    messages: number;
    tickets: number;
    campaigns: number;
    templates: number;
  };
}

export interface AdminUserRow {
  id: string;
  email: string;
  name: string;
  initials: string;
  color: string;
  status: string;
  role: string;
  isSuperAdmin: boolean;
  workspaceCount: number;
  createdAt: string;
}

// ─── Media library ────────────────────────────────────────────────────────

export interface Media {
  id: string;
  workspaceId: string;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  storedPath: string;
  width: number | null;
  height: number | null;
  uploadedById: string | null;
  createdAt: string;
}

// ─── Social publishing ────────────────────────────────────────────────────

export type PublishChannel = "facebook" | "instagram" | "tiktok";

export interface ChannelResult {
  ok: boolean;
  postId?: string;
  error?: string;
}
