import {
  BadRequestException,
  Body,
  Controller,
  ForbiddenException,
  Headers,
  Post,
  RawBodyRequest,
  Req,
} from "@nestjs/common";
import type { Request } from "express";
import { Public } from "../auth/public.decorator";
import { PrismaService } from "../prisma/prisma.service";
import { RealtimeService } from "../realtime/realtime.service";
import { WhatsAppService } from "./whatsapp.service";
import { AiBridgeService } from "./ai-bridge.service";
import { PipelineAutomationService } from "../tickets/pipeline-automation.service";

/**
 * Inbound endpoint for replies generated by the Kewy AI service.
 *
 * The AI never holds Meta credentials and never talks to Graph — it posts the
 * text here and the CRM delivers it through the same `sendInConversation` path
 * a human reply uses. That keeps every WhatsApp token in one place and means an
 * AI outage cannot affect delivery of anything else.
 *
 * Public route: the caller is a service, not a logged-in user, so the HMAC
 * signature over the raw body is the authentication.
 */
@Controller("ai")
export class AiReplyController {
  constructor(
    private readonly prisma: PrismaService,
    private readonly whatsapp: WhatsAppService,
    private readonly bridge: AiBridgeService,
    private readonly realtime: RealtimeService,
    private readonly pipelineAutomation: PipelineAutomationService,
  ) {}

  /**
   * Deliver an AI-generated reply.
   *
   * SHADOW MODE is the point of `send: false`. The agent runs against real
   * customer messages and records what it *would* have said, without a word
   * reaching the customer. That is how reply quality gets measured before the
   * thing is allowed to speak — the alternative is finding out in production.
   */
  @Public()
  @Post("reply")
  async reply(
    @Req() req: RawBodyRequest<Request>,
    @Headers("x-kewy-signature") signature: string | undefined,
    @Body()
    dto: {
      workspaceId?: string;
      conversationId?: string;
      body?: string;
      /** false => log only, deliver nothing (shadow mode). Defaults to false. */
      send?: boolean;
      /** Optional pipeline stage the agent inferred, by stage groupKey. */
      stageGroupKey?: string;
      /** Agent's own confidence in that stage, 0..1. */
      stageConfidence?: number;
      /** Set when the agent decided a human must take over. */
      escalate?: boolean;
      escalateReason?: string;
    },
  ) {
    // Verify against the RAW body: re-serialising the parsed object would
    // change key order or whitespace and break the signature for a payload
    // that is in fact authentic.
    const raw = req.rawBody?.toString("utf8");
    if (!raw) {
      throw new BadRequestException(
        "Raw body unavailable — rawBody must be enabled on the Nest app for signature verification",
      );
    }
    if (!this.bridge.verifyInboundSignature(raw, signature)) {
      throw new ForbiddenException("Invalid signature");
    }

    const { workspaceId, conversationId, body } = dto;
    if (!workspaceId || !conversationId) {
      throw new BadRequestException("workspaceId and conversationId are required");
    }

    const conv = await this.prisma.conversation.findFirst({
      where: { id: conversationId, workspaceId },
      select: { id: true, contactId: true, aiEnabled: true, aiPausedAt: true },
    });
    if (!conv) throw new BadRequestException("Conversation not found");

    // A human replying takes the thread; the agent's in-flight turn loses.
    // Checked here rather than only at dispatch because the agent may have
    // been thinking for several seconds while staff started typing.
    if (conv.aiPausedAt) {
      return { delivered: false, reason: "paused_by_human" };
    }
    if (!conv.aiEnabled) {
      return { delivered: false, reason: "ai_disabled_for_conversation" };
    }

    if (dto.escalate) {
      await this.prisma.conversation.update({
        where: { id: conv.id },
        data: { escalated: true, aiPausedAt: new Date() },
      });
      this.realtime.emitToWorkspace(workspaceId, "inbox.activity", {
        channel: "whatsapp",
        conversationId: conv.id,
        escalated: true,
        reason: dto.escalateReason ?? null,
      });
      return { delivered: false, reason: "escalated" };
    }

    if (!body?.trim()) throw new BadRequestException("body is required");

    // Shadow mode: persist what the agent would have said, marked from 'ai',
    // but never call Graph. The message is visible to staff in the thread so
    // they can judge quality against the real conversation.
    if (dto.send !== true) {
      const now = new Date();
      await this.prisma.message.create({
        data: {
          workspaceId,
          conversationId: conv.id,
          from: "ai",
          body,
          t: `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`,
          agent: "kewy-ai (shadow)",
        },
      });
      this.realtime.emitToWorkspace(workspaceId, "inbox.activity", {
        channel: "whatsapp",
        conversationId: conv.id,
        shadow: true,
      });
      return { delivered: false, reason: "shadow_mode", logged: true };
    }

    // Live delivery reuses the human send path verbatim, so media handling,
    // wamid capture and delivery-status tracking all behave identically.
    await this.whatsapp.sendInConversation(workspaceId, conv.id, body);

    // An AI reply advances the pipeline exactly as a human reply does. Before
    // this, only a human answer moved new -> contacted, so an AI-served lead
    // would have sat in New forever.
    await this.pipelineAutomation.onOutboundReply(workspaceId, conv.contactId);

    return { delivered: true };
  }
}
