// src/screens/dashboard.jsx — main dashboard

function ScreenDashboard({ setRoute, t }) {
  const isAr = t.lang === "ar";
  const tx = (en, ar) => isAr ? ar : en;

  return (
    <div style={{ overflowY: "auto", flex: 1 }}>
      <PageHeader
        title={tx("Welcome back, Yara", "أهلاً يا يارا")}
        subtitle={tx("Here's how Cedar Group's WhatsApp ran today", "إليك ما حدث على واتساب اليوم")}
        actions={
          <>
            <button className="btn">
              <IconCal w={14} />Last 7 days<IconChevDown w={12} />
            </button>
            <button className="btn primary"><IconBolt w={14} />New campaign</button>
          </>
        }
      />

      <div style={{ padding: "0 24px 24px", display: "grid", gap: 16 }}>
        {/* Stat row */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
          <StatTile label={tx("Conversations","المحادثات")} value="1,832" delta="+12.4%" sub={tx("vs prev 7d","مقارنة بالأسبوع السابق")} spark={DAILY.conversations} />
          <StatTile label={tx("AI resolution","حل بالذكاء")} value="86" unit="%" delta="+4.1pp" sub={tx("Without escalation","بدون تصعيد")} spark={DAILY.ai_pct.map(v=>v*100)} />
          <StatTile label={tx("Avg response","متوسط الرد")} value="19" unit="s" delta="-23s" down={false} sub={tx("First reply","الرد الأول")} spark={DAILY.responseTime.slice().reverse()} invert />
          <StatTile label={tx("Pipeline value","قيمة المبيعات")} value="SAR 412k" delta="+18.2%" sub={tx("Generated by AI","بمساعدة الذكاء")} spark={[120,148,162,178,201,228,242]} />
        </div>

        {/* Main row: chart + agents */}
        <div style={{ display: "grid", gridTemplateColumns: "1.65fr 1fr", gap: 16 }}>
          <div className="card">
            <div className="card-h">
              <div>
                <h3>{tx("Conversations · last 7 days","المحادثات · آخر ٧ أيام")}</h3>
                <div className="sub">{tx("AI handled vs human-assisted","تم بالذكاء مقابل بمساعدة بشرية")}</div>
              </div>
              <div style={{ display: "flex", gap: 14, fontSize: 12 }}>
                <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <span style={{ width: 10, height: 2, background: "var(--accent)" }} /> {tx("AI","ذكاء")}
                </span>
                <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <span style={{ width: 10, height: 2, background: "var(--ink-3)", borderTop: "1px dashed" }} /> {tx("Human","بشري")}
                </span>
              </div>
            </div>
            <div style={{ padding: "16px 16px 8px" }}>
              <AreaChart
                a={[142, 178, 211, 240, 224, 268, 297]}
                b={[42, 34, 37, 36, 37, 41, 45]}
                w={680} h={180}
              />
              <div style={{ display: "flex", justifyContent: "space-between", marginTop: 4, fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--ink-3)" }}>
                {["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d => <span key={d}>{d}</span>)}
              </div>
            </div>
          </div>

          <div className="card">
            <div className="card-h">
              <h3>{tx("Your AI agents","وكلاؤك الذكيون")}</h3>
              <button className="btn ghost sm" onClick={() => setRoute("agents")}>
                {tx("Manage","إدارة")}<IconChev w={12} />
              </button>
            </div>
            <div style={{ padding: 8 }}>
              {AGENTS.filter(a => a.status === "live").map(a => (
                <div key={a.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 8px", borderRadius: 8 }}>
                  <Avatar agent={a} ai size="lg" />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                      <span style={{ fontWeight: 500 }}>{a.name}</span>
                      <Badge kind="ok" dot>live</Badge>
                    </div>
                    <div style={{ fontSize: 12, color: "var(--ink-3)" }}>{a.role} · {a.convs} convos · CSAT {a.csat}</div>
                  </div>
                  <div style={{ width: 64 }}>
                    <Spark values={[8, 14, 12, 18, 20, 22, 28]} w={64} h={22} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Bottom row: live activity + intents + campaigns */}
        <div style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr 1fr", gap: 16 }}>
          <div className="card">
            <div className="card-h">
              <h3>{tx("Live activity","النشاط المباشر")}</h3>
              <span className="badge ai" style={{ background: "var(--accent-soft)" }}>
                <span className="dot" style={{ animation: "pulse 1.5s infinite" }} />
                {tx("streaming","مباشر")}
              </span>
            </div>
            <div style={{ padding: "4px 6px 12px" }}>
              {[
                { who: "Luna", role: "ai", what: tx("booked viewing for","حجزت معاينة لـ"), to: "Reem Al-Qahtani", t: "just now" },
                { who: "Atlas", role: "ai", what: tx("answered order status for","رد على حالة طلب لـ"), to: "Fatima Boutros", t: "1m" },
                { who: "Lina", role: "human", what: tx("took over from","تولّت من"), to: "Atlas → James W.", t: "3m" },
                { who: "Nova", role: "ai", what: tx("qualified lead","أهّل عميلاً محتملاً"), to: "Sven Lindgren", t: "8m" },
                { who: "Atlas", role: "ai", what: tx("escalated reschedule","صعّد إعادة جدولة"), to: "Aisha Rahman", t: "14m" },
                { who: "Luna", role: "ai", what: tx("sent floor plan to","أرسلت مخططًا إلى"), to: "Hugo Martín", t: "22m" },
              ].map((row, i) => (
                <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, padding: "8px 12px", borderRadius: 6 }}>
                  {row.role === "ai"
                    ? <Avatar agent={AGENTS.find(a=>a.name===row.who)} ai size="sm" />
                    : <Avatar name={row.who} color="270" size="sm" />}
                  <div style={{ fontSize: 13, flex: 1 }}>
                    <span style={{ fontWeight: 500 }}>{row.who}</span>
                    <span style={{ color: "var(--ink-2)" }}> {row.what} </span>
                    <span style={{ fontWeight: 500 }}>{row.to}</span>
                  </div>
                  <span className="mono" style={{ fontSize: 11, color: "var(--ink-3)" }}>{row.t}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="card">
            <div className="card-h">
              <h3>{tx("Top intents","أهم النوايا")}</h3>
              <span className="sub">{tx("today","اليوم")}</span>
            </div>
            <div style={{ padding: 16 }}>
              {INTENTS.slice(0, 6).map((it, i) => (
                <div key={it.name} style={{ marginBottom: 10 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 4 }}>
                    <span>{tx(it.name, it.name)}</span>
                    <span className="mono muted">{it.count} · {it.pct}%</span>
                  </div>
                  <div style={{ height: 5, background: "var(--bg-2)", borderRadius: 3, overflow: "hidden" }}>
                    <div style={{ width: `${it.pct * 3}%`, height: "100%", background: "var(--accent)", opacity: 0.4 + i * 0.1 }} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="card">
            <div className="card-h">
              <h3>{tx("Active campaigns","الحملات النشطة")}</h3>
              <button className="btn ghost sm" onClick={() => setRoute("campaigns")}>
                {tx("All","الكل")}<IconChev w={12} />
              </button>
            </div>
            <div style={{ padding: "4px 6px 12px" }}>
              {CAMPAIGNS.filter(c => c.status === "running").slice(0, 3).map(c => (
                <div key={c.id} style={{ padding: "10px 12px", borderRadius: 8, marginBottom: 4 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <span style={{ fontSize: 13, fontWeight: 500, flex: 1 }}>{c.name}</span>
                    <Badge kind="ok" dot>running</Badge>
                  </div>
                  <div style={{ fontSize: 11, color: "var(--ink-3)", marginTop: 4, fontFamily: "var(--font-mono)" }}>
                    {c.recipients.toLocaleString()} · {Math.round(c.read/c.recipients*100)}% read · {c.replied} replies
                  </div>
                  <div style={{ height: 4, background: "var(--bg-2)", borderRadius: 2, marginTop: 8, overflow: "hidden", display: "flex" }}>
                    <div style={{ width: `${c.delivered/c.recipients*100}%`, background: "var(--accent)", opacity: 0.6 }} />
                    <div style={{ width: `${(c.read-c.replied)/c.recipients*100}%`, background: "var(--accent)", opacity: 0.3 }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      <style>{`@keyframes pulse { 0%, 100% { opacity: 1 } 50% { opacity: 0.3 } }`}</style>
    </div>
  );
}

function StatTile({ label, value, unit, delta, sub, spark, invert, down }) {
  const isDown = down ?? (delta && delta.startsWith("-"));
  return (
    <div className="stat">
      <div className="label">
        {label}
        <span style={{ marginInlineStart: "auto" }}><IconMore w={14} /></span>
      </div>
      <div className="value">
        {value}{unit && <span className="unit">{unit}</span>}
      </div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
          <span className={`delta ${isDown ? (invert ? "" : "down") : ""}`}>
            {isDown ? <IconArrowDown w={11} /> : <IconArrowUp w={11} />}
            {delta}
          </span>
          <span style={{ fontSize: 11, color: "var(--ink-3)" }}>{sub}</span>
        </div>
        {spark && <Spark values={spark} w={80} h={24} />}
      </div>
    </div>
  );
}

window.ScreenDashboard = ScreenDashboard;
